-- Generated by OLC on 2026-08-06 22:10:54 — area 'greywater_marsh', 3 mobs.
--
-- DO NOT EDIT. `olc` rewrites this file wholesale and your changes will
-- be lost. Hand-written behaviour — actions, hooks, lfun descriptions —
-- goes in custom.lua, which OLC never reads or writes.
return {
    {
        id           = "marsh_lurker",
        prototype    = "marsh.venomous",
        short        = "a marsh lurker",
        description  = "Long, flat and the colour of the bottom, with a mouth that opens further back than a mouth should. It is only visible when it moves, and it does not often move.",
        stats        = {
            constitution = 11,
            dexterity    = 14,
            hp           = 45,
            level        = 5,
            max_hp_flat  = 45,
            strength     = 13,
        },
        damage       = { min = 4, max = 9 },
        xp_award     = 60,
        spawn_room   = "greywater_marsh.stilt_village",
        count        = 2,
        respawn_time = 240,
        loot_table   = {
            { chance = 0.4, item_id = "dried_marshroot" },
        },
    },
    {
        id           = "reed_crawler",
        prototype    = "marsh.crawler",
        short        = "a reed crawler",
        description  = "Waist high, many-legged, and it walks on the reeds rather than through them. It has no eyes anyone has found.",
        stats        = {
            constitution = 9,
            dexterity    = 16,
            hp           = 30,
            level        = 3,
            max_hp_flat  = 30,
            strength     = 10,
        },
        damage       = { min = 2, max = 6 },
        xp_award     = 30,
        spawn_room   = "greywater_marsh.herb_beds",
        count        = 3,
        respawn_time = 180,
    },
    {
        id           = "greywater_wisp",
        name         = "wisp",
        short        = "a pale wisp",
        description  = "A hand-sized light with nothing holding it up, the colour of a candle seen through water. It keeps exactly the distance it wants and no other.",
        body         = "amorphous",
        faction      = "marsh",
        stats        = {
            constitution = 14,
            dexterity    = 20,
            hp           = 80,
            intelligence = 18,
            level        = 10,
            max_hp_flat  = 80,
            strength     = 8,
            wisdom       = 16,
        },
        damage       = { min = 8, max = 14 },
        damage_type  = "magic",
        xp_award     = 200,
        aggressive   = true,
        unique       = true,
        spawn_room   = "greywater_marsh.deep_water",
        count        = 1,
        respawn_time = 900,
        dialogue     = {
            greeting = "The light does not change. After a moment you realise it has moved closer without appearing to move.",
        },
        loot_table   = {
            { chance = 0.25, item_id = "warded_cloak" },
            { chance = 0.15, item_id = "silver_dagger" },
        },
        tags         = { "magical", "unique", "marsh" },
    },
}
