-- Area metadata, generated by OLC on 2026-08-06 02:51:02.
--
-- `managed` is what lets OLC write here at all. Remove it and every
-- OLC write to this area is refused — which is how a hand-authored
-- area stays safe from a regeneration that would eat its lfuns.
return {
    name     = "crypt",
    title    = "The Sunken Crypt",
    author   = "sheridan",
    level    = nil,
    entrance = "crypt.entrance",
    status   = "building",
    managed  = "olc.v1",
    updated  = "2026-08-06 02:51:02",
}
