-- Generated by OLC on 2026-08-06 02:57:07 — area 'crypt', 2 rooms.
--
-- DO NOT EDIT. `olc` rewrites this file wholesale and your changes will
-- be lost. Hand-written behaviour — actions, hooks, lfun descriptions —
-- goes in custom.lua, which OLC never reads or writes.
return {
    {
        id          = "crypt.entrance",
        short       = "The Entrance",
        description = "You are in a room.",
        light       = 1,
        tags        = {},
        exits       = { north = "crypt.hall" },
        items       = {},
    },
    {
        id          = "crypt.hall",
        short       = "The Great Hall",
        description = "You are in a long hall, cleared by the ravages of time. There is a statue of owllex in the center. It looks very handsome, and you wonder how long it has been here.",
        light       = 1,
        tags        = {},
        exits       = { south = "crypt.entrance" },
        items       = {},
    },
}
