-- Area metadata, generated by OLC on 2026-08-06 22:10:54.
--
-- `managed` is what lets OLC write here at all. Remove it and every
-- OLC write to this area is refused — which is how a hand-authored
-- area stays safe from a regeneration that would eat its lfuns.
return {
    name     = "greywater_marsh",
    title    = "Greywater Marsh",
    author   = "Oxigeon",
    level    = "3-12",
    entrance = "greywater_marsh.causeway_head",
    status   = "live",
    managed  = "olc.v1",
    updated  = "2026-08-06 22:10:54",
}
