-- Generated by OLC on 2026-08-06 22:10:54 — area 'greywater_marsh', 5 rooms.
--
-- DO NOT EDIT. `olc` rewrites this file wholesale and your changes will
-- be lost. Hand-written behaviour — actions, hooks, lfun descriptions —
-- goes in custom.lua, which OLC never reads or writes.
return {
    {
        id    = "greywater_marsh.causeway_head",
        short = "The Head of the Causeway",
        light = 3,
        smell = "Standing water and rot, and under it something mineral.",
        tags  = { "outdoor", "marsh" },
        exits = {
            east = "thornhollow.west_gate",
            west = "greywater_marsh.causeway_mid",
        },
        items = {
            cairns = "Stacked flat stones, waist high. Several have been pushed over, which took some doing.",
            reeds  = "Grey-green and taller than a person. They move when there is no wind, which the townsfolk say is fish.",
        },
    },
    {
        id    = "greywater_marsh.causeway_mid",
        short = "The Causeway",
        light = 2,
        smell = "Rot, closer now.",
        sound = "Water under the stone, which should not be possible.",
        tags  = { "outdoor", "marsh" },
        exits = {
            north = "greywater_marsh.herb_beds",
            east  = "greywater_marsh.causeway_head",
            west  = "greywater_marsh.stilt_village",
        },
        items = {
            joints = "The stone joints have opened. Water goes under here.",
            willow = "A drowned willow, dead for years and still standing, holding up a mat of reed and worse.",
        },
    },
    {
        id    = "greywater_marsh.herb_beds",
        short = "The Herb Beds",
        light = 2,
        smell = "Green, and sharply medicinal.",
        sound = "Insects, in a marsh that has almost nothing else living in it.",
        tags  = { "outdoor", "marsh", "resource" },
        exits = { south = "greywater_marsh.causeway_mid" },
        items = {
            root   = "Pale forked marshroot, growing in the shallows. Warm to the touch, which nobody has explained.",
            stakes = "Marker stakes, several of them new. Whatever moves them does not take them away.",
        },
    },
    {
        id    = "greywater_marsh.stilt_village",
        short = "The Stilt Village",
        light = 1,
        smell = "Wet timber and old smoke.",
        sound = "Timber working against timber, all around, at no particular rate.",
        tags  = { "outdoor", "marsh", "ruin" },
        exits = {
            east = "greywater_marsh.causeway_mid",
            west = "greywater_marsh.deep_water",
        },
        items = {
            houses = "Eleven houses on oak piles. The doors are open and the shelves are not empty.",
            pots   = "Cooking pots, still on their shelves, with the handles worn where somebody held them.",
        },
    },
    {
        id    = "greywater_marsh.deep_water",
        short = "The Deep Water",
        light = 1,
        smell = "Cold. Only cold.",
        sound = "Nothing above the water at all.",
        tags  = { "outdoor", "marsh", "dangerous" },
        exits = { east = "greywater_marsh.stilt_village" },
        items = {
            stones = "Pale flat stones, laid in a line out into the deep water. They are laid, not fallen.",
        },
    },
}
