-- Area metadata, generated by OLC on 2026-08-06 22:11:56.
--
-- `managed` is what lets OLC write here at all. Remove it and every
-- OLC write to this area is refused — which is how a hand-authored
-- area stays safe from a regeneration that would eat its lfuns.
return {
    name     = "wizard_workshop",
    title    = "The Wizard's Workshop",
    author   = "Oxigeon",
    level    = "1-5",
    entrance = "wizard_workshop.entrance",
    status   = "live",
    managed  = "olc.v1",
    updated  = "2026-08-06 22:11:56",
}
