-- Generated by OLC on 2026-08-06 23:48:49 — area 'wizard_workshop', 4 mobs.
--
-- DO NOT EDIT. `olc` rewrites this file wholesale and your changes will
-- be lost. Hand-written behaviour — actions, hooks, lfun descriptions —
-- goes in custom.lua, which OLC never reads or writes.
return {
    { id = "black_rat", prototype = "vermin.rat.black" },
    { id = "scrawny_rat", prototype = "vermin.rat.scrawny" },
    { id = "muscular_rat", prototype = "vermin.rat.muscular" },
    {
        id           = "dust_mephit",
        name         = "mephit",
        short        = "a swirling dust mephit",
        description  = "A knee-high creature of animate dust and static, held together by a spell nobody remembered to end. It regards you with the sullen resentment of something that would rather be a cloud.",
        body         = "amorphous",
        stats        = {
            constitution = 12,
            dexterity    = 9,
            hp           = 40,
            intelligence = 6,
            level        = 3,
            max_hp_flat  = 40,
            strength     = 10,
            wisdom       = 8,
        },
        damage       = { min = 4, max = 8 },
        xp_award     = 35,
        aggressive   = false,
        spawn_room   = "wizard_workshop.laboratory",
        count        = 1,
        respawn_time = 300,
        tags         = { "elemental", "magical" },
    },
}
