-- Generated by OLC on 2026-08-06 23:48:47 — area 'wizard_workshop', 6 rooms.
--
-- DO NOT EDIT. `olc` rewrites this file wholesale and your changes will
-- be lost. Hand-written behaviour — actions, hooks, lfun descriptions —
-- goes in custom.lua, which OLC never reads or writes.
return {
    {
        id          = "wizard_workshop.entrance",
        short       = "Entrance to the Workshop",
        description = [[
You stand in a circular foyer choked with decades of dust. A heavy oak door,
banded with iron and etched with faded protective wards, stands ajar to the
east — the wards on it went out a long time ago, and beyond it is the cold
stone of the town undercroft. The air is still, yet motes of dust dance as if
caught in invisible currents of residual magic. Along the curved walls,
tarnished coat hooks hold the moth-eaten remains of heavy velvet robes.]],
        light       = 1,
        smell       = "Old dust and faint ozone.",
        sound       = "The faint hum of magical wards struggling to persist.",
        exits       = {
            north = "wizard_workshop.laboratory",
            east  = "thornhollow.undercroft",
        },
        items       = {
            door  = "The heavy oak door is covered in faded silver runes — protective wards, long since weakened by time.",
            robes = "Moth-eaten velvet robes hang limply from the hooks. They might have been magnificent once, dyed deep purple with gold trim.",
        },
    },
    {
        id    = "wizard_workshop.laboratory",
        short = "The Alchemical Laboratory",
        light = 2,
        smell = "A sharp, acrid tang of sulfur and burnt sugar.",
        sound = "A slow, rhythmic bubbling from a sealed glass retort.",
        exits = {
            north = "wizard_workshop.archive",
            south = "wizard_workshop.entrance",
            east  = "wizard_workshop.scrying_chamber",
            west  = "wizard_workshop.pantry",
        },
        items = {
            magelight = "The hovering magelight is a pale sphere of bluish-white energy, flickering erratically. It seems to be running low on whatever power sustains it.",
            workbench = "The oak workbench is deeply scarred by decades of acid spills and scorch marks. Crystallized reagent stains glitter across its surface like tiny gemstones.",
        },
    },
    {
        id             = "wizard_workshop.pantry",
        short          = "Reagent Pantry",
        description    = [[
Shadows cling tightly to the corners of this narrow, cramped storage room.
Towering shelves groan under the weight of hundreds of glass jars containing
strange, unidentifiable contents. Pickled eyes bob lazily in formaldehyde,
glowing blue fungi pulse with a faint luminescence, and bundles of dried herbs
hang upside down from the ceiling rafters. It feels as though the ingredients
themselves are watching you.]],
        light          = 1,
        smell          = "An overwhelming blend of dried mint, decay, and sharp vinegar.",
        sound          = "The rustling of dried leaves disturbed by unseen drafts.",
        exits          = { east = "wizard_workshop.laboratory" },
        items          = {
            fungi = "The glowing blue fungi pulse rhythmically, like a slow heartbeat, casting eerie shadows behind the jars.",
            jars  = "Hundreds of glass jars line the shelves, their contents ranging from mundane dried herbs to deeply unsettling specimens floating in murky preservatives.",
            nest  = "Behind the lowest shelf, a heap of shredded parchment, gnawed cork and one entire glove. It is warm. Something in it moves when you look away from it.",
        },
        spawn_max      = 3,
        spawn_interval = 45,
        spawn_table    = {
            { template = "black_rat", weight = 5 },
            { template = "scrawny_rat", weight = 3 },
            { template = "muscular_rat", weight = 1 },
        },
    },
    {
        id          = "wizard_workshop.scrying_chamber",
        short       = "The Scrying Chamber",
        description = [[
Thick, moth-eaten velvet curtains drape the walls of this circular room,
absorbing all ambient light and sound. In the center stands a large obsidian
mirror, its surface swirling with a milky, churning fog that seems to pull at
your gaze. Intricate star charts and astrological alignments are chalked into
the floorboards, their lines worn but still humming with faint divination magic.]],
        light       = 1,
        smell       = "A metallic scent of ozone, like the air after a fierce lightning storm.",
        sound       = "An absolute, oppressive silence that rings in your ears.",
        exits       = { west = "wizard_workshop.laboratory" },
        items       = {
            charts = "Star charts and astrological alignments are chalked in precise detail across the floorboards, mapping constellations you don't recognize.",
            mirror = "The obsidian mirror's surface churns with milky fog. For a moment, you think you see a face staring back — but it isn't yours.",
        },
    },
    {
        id          = "wizard_workshop.archive",
        short       = "The Forbidden Archive",
        description = [[
Floor-to-ceiling bookshelves curve along the walls, packed tight with ancient,
leather-bound grimoires and crumbling scrolls. A heavy oak reading desk sits near
a shattered stained-glass window, covered in spilled ink and discarded quills.
The knowledge contained within these fragile pages feels palpable, an electric
tension in the air that raises the hairs on your arms. A few books float lazily
a few inches off the shelves, trapped in localized gravity anomalies.]],
        light       = 2,
        smell       = "The comforting, rich scent of old leather and foxed pages.",
        sound       = "The soft flutter of pages turning on their own.",
        exits       = { south = "wizard_workshop.laboratory" },
        items       = {
            books = "The grimoires are bound in dark leather, some chained to the shelves. A few float lazily, trapped in localized gravity anomalies.",
            desk  = "The reading desk is covered in spilled ink, broken quill nibs, and half-finished notes in a cramped, frantic handwriting. Sitting among the clutter is a small, empty crystal vial — its glass so thin it's almost invisible.",
            vial  = "A small, empty crystal vial sits on the desk. The glass is paper-thin and perfectly clear. It looks like it was made for collecting alchemical samples.",
        },
    },
    {
        id    = "wizard_workshop.treasure_vault",
        short = "The Hidden Treasure Vault",
        light = 3,
        smell = "Cold stone and the metallic tang of rare alloys.",
        sound = "A deep, resonant hum that seems to emanate from the metal itself.",
        exits = {},
        items = {
            bars      = "Bars of manasteel, each about a foot long and incredibly dense. The metal has a liquid-silver sheen and seems to vibrate faintly when touched.",
            crystal   = "Veins of luminous crystal thread through the rock walls, pulsing with a slow blue rhythm — like a heartbeat. They provide all the light in this sealed chamber.",
            manasteel = "Bars of manasteel, each about a foot long and incredibly dense. The metal has a liquid-silver sheen and seems to vibrate faintly when touched. This is one of the rarest crafting materials in existence.",
            orb       = "The crystalline orb is perfectly spherical, about the size of a fist. Inside, you can see what looks like a miniature storm of violet lightning. It rotates slowly above its pedestal, humming with power.",
            pedestal  = "A simple stone pedestal, worn smooth by ages. The crystalline orb hovers above it without any visible support.",
        },
    },
}
