-- Generated by OLC on 2026-08-06 22:19:44 — area 'thornhollow', 10 rooms.
--
-- DO NOT EDIT. `olc` rewrites this file wholesale and your changes will
-- be lost. Hand-written behaviour — actions, hooks, lfun descriptions —
-- goes in custom.lua, which OLC never reads or writes.
return {
    {
        id          = "thornhollow.square",
        short       = "Thornhollow Square",
        description = [[
The square is a lopsided rectangle of packed earth with a stone well off centre,
as if the town grew around the water rather than the other way about. Buildings
lean inward on three sides — the market arcade to the east, the smithy's
chimney smoking to the north, and the low black mouth of the undercroft stair
going down beside the chapel. West, past the last house, the road gives up and
becomes a track toward the marsh.]],
        light       = 3,
        smell       = "Woodsmoke, wet stone and something sour off the marsh.",
        sound       = "The creak of the well rope and two people arguing about a goat.",
        tags        = { "outdoor", "town", "safe" },
        exits       = {
            north = "thornhollow.smithy",
            south = "thornhollow.tavern",
            east  = "thornhollow.market",
            west  = "thornhollow.west_gate",
            down  = "thornhollow.undercroft_stair",
        },
        items       = {
            board  = "A notice board thick with parchment, most of it illegible. The top layer is fresh.",
            chapel = "A small chapel with a slate roof and no bell. The door is shut but not locked.",
            well   = "A stone well, its rim worn into a shallow saddle by three hundred years of rope. The bucket is newer than the rope.",
        },
    },
    {
        id          = "thornhollow.smithy",
        short       = "Bellow & Son, Smiths",
        description = [[
Heat comes off the forge in slabs. The walls are hung with work in every stage
of finish — blanks, half-ground blades, a mail shirt with one sleeve. A long
bench runs under the window, and everything on it has been put down mid-job and
left there. There is no son.]],
        light       = 2,
        smell       = "Hot iron, quench-water and coal.",
        sound       = "The uneven ring of a hammer that stops whenever you speak.",
        tags        = { "indoor", "town", "shop", "safe" },
        exits       = { south = "thornhollow.square", down = "collapsed_mine.adit" },
        items       = {
            forge = "A brick forge, banked rather than lit. The coal in it is good coal, which says something about the year.",
            mail  = "A mail shirt hanging from a nail, finished except for one sleeve. It has been finished except for one sleeve for a long time.",
        },
    },
    {
        id          = "thornhollow.tavern",
        short       = "The Drowned Bell",
        description = [[
The common room of the Drowned Bell is darker than the hour warrants, on
purpose. A bell hangs behind the bar, green with corrosion, dredged out of the
reach by someone's grandfather; nobody agrees which one. The tables are set far
enough apart that two conversations do not have to be one.]],
        light       = 1,
        smell       = "Spilled ale, tallow and old rushes.",
        sound       = "Low talk that drops whenever the door opens.",
        tags        = { "indoor", "town", "safe", "social" },
        exits       = { north = "thornhollow.square" },
        items       = {
            bell   = "A ship's bell, corroded to the colour of pond weed. Struck, it makes almost no sound at all.",
            hearth = "A wide hearth with a fire in it that somebody keeps small on purpose.",
        },
    },
    {
        id          = "thornhollow.west_gate",
        short       = "The West Gate",
        description = [[
Two posts and a rail that has not been a gate for some years. Past it the road
stops pretending and becomes a causeway of laid stone running west into
Greywater — grey water, grey reed, grey light. A board nailed to the left post
reads DO NOT LEAVE THE STONE in letters that have been repainted.]],
        light       = 3,
        smell       = "Standing water, and the wind off it.",
        sound       = "Reeds, and further off, water moving where it should not.",
        tags        = { "outdoor", "town", "border" },
        exits       = {
            east = "thornhollow.square",
            west = "greywater_marsh.causeway_head",
        },
        items       = {
            board = "DO NOT LEAVE THE STONE. Repainted, more than once, by someone who did not think the first two attempts had worked.",
            posts = "Two oak posts with hinge marks and no hinges.",
        },
    },
    {
        id          = "thornhollow.market",
        short       = "The Market Arcade",
        description = [[
The arcade is a stone tunnel with the shopfronts cut into its sides, roofed
because the town has more rain than money. Trestles run down the middle on
market days and are stacked against the wall on every other. The far end opens
onto the apothecary's steps; the near end gives back onto the square.]],
        light       = 2,
        smell       = "Dried herbs, sawdust and wet wool.",
        sound       = "Two dozen conversations under a low stone ceiling.",
        tags        = { "indoor", "town", "safe", "social" },
        exits       = {
            north = "thornhollow.general_store",
            south = "thornhollow.apothecary",
            west  = "thornhollow.square",
        },
        items       = {
            ceiling  = "Low stone vaulting, sooted black above each shopfront.",
            trestles = "Stacked trestle tables, worn pale where things have been put down on them.",
        },
    },
    {
        id          = "thornhollow.general_store",
        short       = "Hobb's Provisions",
        description = [[
Every wall is shelf and every shelf is full, in the manner of a shop that has
never once thrown anything away. Rope, lamp oil, sacking, biscuit, nails by the
scoop. A hand-lettered card by the door reads NO CREDIT, and under it, in a
different hand, NOT EVEN YOU.]],
        light       = 2,
        smell       = "Rope, tallow and dried fish.",
        sound       = "Something small moving in the back, which Hobb ignores.",
        tags        = { "indoor", "town", "shop", "safe" },
        exits       = { south = "thornhollow.market" },
        items       = {
            card    = "NO CREDIT. And beneath, in a different and angrier hand, NOT EVEN YOU.",
            shelves = "Shelves to the ceiling, arranged by no system anyone but Hobb could reconstruct.",
        },
    },
    {
        id          = "thornhollow.apothecary",
        short       = "The Apothecary's Steps",
        description = [[
Six steps down into a room the width of two people. Bunches hang drying from
every beam, so low that anyone tall walks bent. The counter is a plank across
two barrels, and behind it the wall is entirely small drawers, each labelled in
a hand that got smaller as it ran out of room.]],
        light       = 1,
        smell       = "Bitter green things, and under it something medicinal and old.",
        sound       = "A slow drip into a copper basin.",
        tags        = { "indoor", "town", "shop", "safe" },
        exits       = { north = "thornhollow.market" },
        items       = {
            bunches = "Herbs hung to dry. Some of them are from the marsh, which is not a thing most towns would allow indoors.",
            drawers = "Two hundred small drawers, labelled in a hand that got steadily smaller as the labeller ran out of wall.",
        },
    },
    {
        id          = "thornhollow.undercroft_stair",
        short       = "The Undercroft Stair",
        description = [[
Twelve steps down, cut rather than laid, with a rope handrail that has been
replaced more recently than anything else here. The light from the square
reaches four of the steps. A lantern bracket at the bottom holds no lantern.]],
        light       = 1,
        smell       = "Cold stone and candle smoke.",
        sound       = "Your own feet, louder than you expected.",
        tags        = { "indoor", "town", "underground" },
        exits       = { up = "thornhollow.square", down = "thornhollow.undercroft" },
        items       = {
            bracket = "An iron lantern bracket, empty, with a ring of old soot on the stone above it.",
            rope    = "A rope handrail, newer than the steps by three centuries.",
        },
    },
    {
        id          = "thornhollow.undercroft",
        short       = "The Undercroft",
        description = [[
A vaulted room the footprint of the chapel above it, kept dry by something
nobody in the town can explain and nobody wants explained. The town's strongbox
sits against the north wall on a plinth, under the one bracket that does hold a
lantern. An arch east leads to the older part, where the crypt is.]],
        light       = 1,
        smell       = "Dry dust, which is a surprise this close to the marsh.",
        sound       = "Nothing at all, and it takes a moment to notice.",
        tags        = { "indoor", "town", "underground", "safe" },
        exits       = {
            east = "thornhollow.crypt",
            west = "wizard_workshop.entrance",
            up   = "thornhollow.undercroft_stair",
        },
        items       = {
            door    = "An oak door in the west wall, banded with iron and covered in silver runes that have stopped meaning anything. It stands ajar. It has stood ajar for years.",
            lantern = "A lantern in a bracket, lit. Somebody comes down to see to it, and nobody has ever said who.",
            plinth  = "A stone plinth, worn on top where the strongbox has been dragged on and off it.",
        },
    },
    {
        id          = "thornhollow.crypt",
        short       = "The Old Crypt",
        description = [[
The older part, and it does not match: the vaulting here is round rather than
pointed, and the floor is flagstones rather than beaten chalk. Names are cut
into the walls in a script the chapel above does not use. One flagstone near the
east wall sits a finger higher than the rest.]],
        light       = 0,
        smell       = "Stone, and the ghost of incense.",
        sound       = "A drip somewhere behind the wall, not in the room.",
        tags        = { "indoor", "town", "underground", "dark" },
        exits       = { west = "thornhollow.undercroft" },
        items       = {
            flagstone = "One flagstone sits a finger proud of the others. It has been lifted before.",
            names     = "Names cut into the wall, in a script that reads left to right and then right to left, alternating.",
        },
    },
}
