-- Generated by OLC on 2026-08-06 22:17:37 — area 'collapsed_mine', 4 items.
--
-- DO NOT EDIT. `olc` rewrites this file wholesale and your changes will
-- be lost. Hand-written behaviour — actions, hooks, lfun descriptions —
-- goes in custom.lua, which OLC never reads or writes.
return {
    {
        id          = "iron_ore",
        short       = "a lump of iron ore",
        description = "Heavy for its size, rust-coloured, and warm on one face where it came off the seam.",
        weight      = 4,
        value       = 25,
        stackable   = true,
        quantity    = 1,
        equippable  = false,
        always_lit  = false,
        tags        = { "ore", "reagent" },
    },
    {
        id                = "miners_pick",
        components        = { "weapon" },
        short             = "a long-handled miner's pick",
        description       = "Four feet of ash with a steel head, one point and one blade. It is a tool that a desperate person can use twice.",
        weight            = 9,
        value             = 55,
        stackable         = false,
        quantity          = 1,
        slot              = "weapon",
        equippable        = true,
        always_lit        = false,
        tags              = { "weapon", "tool" },

        -- weapon
        damage            = { min = 6, max = 12 },
        speed             = 0.8,
        weapon_type       = "pick",
        length            = 60,
        parry             = true,
        damage_type       = "physical",
        two_handed        = true,
        range             = "melee",
        hit_message       = "You bring the pick down on {target} point-first.",

        -- requires
        required_strength = 13,
    },
    {
        id             = "delvers_claw",
        components     = { "weapon" },
        short          = "a Delver's claw",
        description    = "Taken off the thing itself: a foot of something between horn and slate, still warm. Held at the base it is a weapon, and held anywhere else it is a mistake.",
        weight         = 5,
        value          = 800,
        stackable      = false,
        quantity       = 1,
        slot           = "weapon",
        equippable     = true,
        always_lit     = false,
        tags           = { "weapon", "boss" },

        -- weapon
        damage         = { min = 11, max = 19 },
        speed          = 1,
        weapon_type    = "claw",
        length         = 40,
        parry          = true,
        damage_type    = "physical",
        two_handed     = false,
        range          = "melee",
        hit_message    = "The claw goes into {target} the way it was made to.",
        crit_message   = "The claw finds the gap it was looking for.",

        -- requires
        required_level = 12,
    },
    {
        id              = "delver_corpse",
        components      = { "container" },
        short           = "the Delver's corpse",
        description     = "Long-armed and much too deliberate even now. Something in it is still warm.",
        weight          = 300,
        value           = 0,
        stackable       = false,
        quantity        = 1,
        equippable      = false,
        always_lit      = false,
        tags            = { "container", "corpse" },

        -- container
        capacity        = 0,
        capacity_weight = 0,
        closeable       = false,
        starts_closed   = false,
        starts_locked   = false,
    },
}
