-- Generated by OLC on 2026-08-06 22:17:37 — area 'collapsed_mine', 3 mobs.
--
-- DO NOT EDIT. `olc` rewrites this file wholesale and your changes will
-- be lost. Hand-written behaviour — actions, hooks, lfun descriptions —
-- goes in custom.lua, which OLC never reads or writes.
return {
    {
        id           = "mine_crawler",
        prototype    = "mine.crawler",
        short        = "a pale mine crawler",
        description  = "The same shape as the reed crawlers in the marsh and half again the size, and this one has no colour at all.",
        stats        = {
            constitution = 13,
            dexterity    = 12,
            hp           = 55,
            level        = 7,
            max_hp_flat  = 55,
            strength     = 14,
        },
        damage       = { min = 5, max = 11 },
        xp_award     = 90,
        spawn_room   = "collapsed_mine.first_level",
        count        = 2,
        respawn_time = 300,
        loot_table   = {
            { chance = 0.3, item_id = "iron_ore" },
        },
    },
    {
        id           = "shale_lurker",
        prototype    = "mine.lurker",
        short        = "something under the shale",
        description  = "You can see where it is by where the floor is not level. That is all you can see of it.",
        stats        = {
            constitution = 14,
            dexterity    = 15,
            hp           = 70,
            level        = 9,
            max_hp_flat  = 70,
            strength     = 16,
        },
        damage       = { min = 7, max = 13 },
        xp_award     = 130,
        spawn_room   = "collapsed_mine.deep_workings",
        respawn_time = 420,
    },
    {
        id           = "the_delver",
        name         = "delver",
        short        = "the Delver",
        description  = "It is the shape of the thing that made the tool marks: long-armed, working from the elbow, and much too deliberate. It stops when you look at it and starts again when you do not.",
        body         = "humanoid",
        faction      = "mine",
        stats        = {
            constitution = 20,
            dexterity    = 14,
            hp           = 260,
            intelligence = 12,
            level        = 15,
            max_hp_flat  = 260,
            strength     = 22,
            wisdom       = 14,
        },
        damage       = { min = 12, max = 22 },
        xp_award     = 900,
        aggressive   = true,
        unique       = true,
        spawn_room   = "collapsed_mine.the_sump",
        count        = 1,
        respawn_time = 1800,
        loot_table   = {},
        tags         = { "boss", "unique", "mine" },
    },
}
