-- Generated by OLC on 2026-08-06 22:17:37 — area 'collapsed_mine', 6 rooms.
--
-- DO NOT EDIT. `olc` rewrites this file wholesale and your changes will
-- be lost. Hand-written behaviour — actions, hooks, lfun descriptions —
-- goes in custom.lua, which OLC never reads or writes.
return {
    {
        id          = "collapsed_mine.adit",
        short       = "The Mine Adit",
        description = [[
The mouth of the mine, timbered and still square after two years of nobody
maintaining it. A rail runs in and stops at a tub with one wheel. Daylight gets
about thirty feet and then gives up entirely, which is where the first level
starts.]],
        light       = 2,
        smell       = "Cold rock and old blasting powder.",
        sound       = "Water, a long way down, doing something regular.",
        tags        = { "indoor", "mine", "underground" },
        exits       = { up = "thornhollow.smithy", down = "collapsed_mine.first_level" },
        items       = {
            rail = "Iron rail, still bright on the top where the tub ran.",
            tub  = "An ore tub with one wheel and no other wheel. Somebody took the other wheel.",
        },
    },
    {
        id          = "collapsed_mine.first_level",
        short       = "The First Level",
        description = [[
A gallery following the seam, propped every eight feet with timber that has gone
grey. The floor is loose shale and it moves. Someone has painted arrows on the
props at knee height, all pointing back the way you came.]],
        light       = 0,
        smell       = "Rock dust, and something metallic under it.",
        sound       = "Your own breathing, coming back off a wall you cannot see.",
        tags        = { "indoor", "mine", "underground", "dark" },
        exits       = { up = "collapsed_mine.adit", down = "collapsed_mine.second_level" },
        items       = {
            arrows = "Arrows painted at knee height on every prop, all pointing out. Painted by somebody who expected to be crawling.",
            seam   = "A band of darker rock running along the wall at chest height. There is metal in it.",
        },
    },
    {
        id    = "collapsed_mine.second_level",
        short = "The Second Level",
        light = 0,
        smell = "Wet rock. It is warmer here than it should be.",
        sound = "The pipes overhead, which are dry and should not be.",
        tags  = { "indoor", "mine", "underground", "dark" },
        exits = {
            east = "collapsed_mine.pump_house",
            up   = "collapsed_mine.first_level",
        },
        items = {
            grille = "Cast iron on runners, with a lock let into the frame. The lock is newer than the mine.",
            pipes  = "Iron pipes along the ceiling, running east. Dry, which means the pump is not running.",
        },
    },
    {
        id    = "collapsed_mine.pump_house",
        short = "The Pump House",
        light = 1,
        smell = "Grease, and the particular smell of cold cast iron.",
        tags  = { "indoor", "mine", "underground" },
        exits = { west = "collapsed_mine.second_level" },
        items = {
            engine = "A beam engine, cold. The bearings have been greased recently, which nobody in town admits to.",
            levers = "Three levers in a rack: left, middle and right. The plates above them are illegible.",
            plates = "Brass plates, green and unreadable. One of them has been scratched with a tally: one line, two lines, three lines, left to right.",
        },
    },
    {
        id    = "collapsed_mine.deep_workings",
        short = "The Deep Workings",
        light = 0,
        smell = "Water, and under the water something organic.",
        sound = "Dripping, and further in, something that is not dripping.",
        tags  = { "indoor", "mine", "underground", "dark", "dangerous" },
        exits = { east = "collapsed_mine.second_level" },
        items = {
            marks = "Tool marks, too broad for a pick and angled wrongly. Whatever made them worked from the elbow.",
            water = "Black standing water, two feet of it, with no bottom visible.",
        },
    },
    {
        id          = "collapsed_mine.the_sump",
        short       = "The Sump",
        description = [[
The bottom of the shaft opens into a chamber that nobody cut. The walls are the
same rounded cut as the workings above and they go all the way round, and the
floor is a floor because things have been put on it: rail, timber, a tub, a
boot. It is a nest, and it has been a nest for longer than the mine has been
shut.]],
        light       = 0,
        smell       = "The bottom of the world.",
        sound       = "One sound, repeating, that is not water.",
        tags        = { "indoor", "mine", "underground", "dark", "dangerous", "boss" },
        exits       = { up = "collapsed_mine.deep_workings" },
        items       = {
            boot = "A miner's boot, laced. It has been placed rather than dropped.",
            nest = "Rail, timber, an ore tub and one boot, arranged. Arranged is the word that stays with you.",
        },
    },
}
