-- Area metadata, generated by OLC on 2026-08-06 22:17:37.
--
-- `managed` is what lets OLC write here at all. Remove it and every
-- OLC write to this area is refused — which is how a hand-authored
-- area stays safe from a regeneration that would eat its lfuns.
return {
    name     = "collapsed_mine",
    title    = "The Collapsed Mine",
    author   = "Oxigeon",
    level    = "5-15",
    entrance = "collapsed_mine.adit",
    status   = "live",
    managed  = "olc.v1",
    updated  = "2026-08-06 22:17:37",
}
