-- game/daemons/codegen_d.lua — OLC code generation daemon
-- Generates clean, human-readable Lua data files for areas and rooms.
-- Handles round-tripping: read existing files, modify, regenerate.

local M = {}

-- ─── Room file generation ────────────────────────────────────────────────────

--- Generate Lua source for a single room data file.
-- @param room_id string       Full room ID (area.room)
-- @param data table           Room data { short, description, exits, items, builder }
-- @return string              Lua source code
function M.generate_room(room_id, data)
    local lines = {}
    local builder = data.builder or "Unknown"
    local timestamp = os_date("%Y-%m-%d %H:%M:%S")

    lines[#lines + 1] = "-- Generated by OLC on " .. timestamp
    lines[#lines + 1] = "-- Builder: " .. builder
    lines[#lines + 1] = "return {"
    lines[#lines + 1] = '    id = "' .. room_id .. '",'

    -- Short description
    if data.short then
        lines[#lines + 1] = '    short = "' .. data.short .. '",'
    end

    -- Long description — use [[ ]] for multi-line
    local desc = data.description or "A bare room awaiting description."
    if desc:find("\n") then
        lines[#lines + 1] = "    description = [["
        lines[#lines + 1] = desc
        lines[#lines + 1] = "    ]],"
    else
        lines[#lines + 1] = '    description = [[' .. desc .. ']],'
    end

    -- Exits
    if data.exits and next(data.exits) then
        lines[#lines + 1] = "    exits = {"
        -- Sort directions for deterministic output
        local dirs = {}
        for dir in pairs(data.exits) do dirs[#dirs + 1] = dir end
        table.sort(dirs)
        for _, dir in ipairs(dirs) do
            lines[#lines + 1] = '        ' .. dir .. ' = "' .. data.exits[dir] .. '",'
        end
        lines[#lines + 1] = "    },"
    end

    -- Items (scenery)
    if data.items and next(data.items) then
        lines[#lines + 1] = "    items = {"
        for keyword, description in pairs(data.items) do
            lines[#lines + 1] = '        ' .. keyword .. ' = "' .. description .. '",'
        end
        lines[#lines + 1] = "    },"
    end

    lines[#lines + 1] = "}"
    lines[#lines + 1] = ""

    return table.concat(lines, "\n")
end

-- ─── Meta file generation ────────────────────────────────────────────────────

--- Generate Lua source for an area _meta.lua file.
-- @param area_name string
-- @param meta_data table   { name, title, author, status, ... }
-- @return string           Lua source code
function M.generate_meta(area_name, meta_data)
    local lines = {}
    local timestamp = os_date("%Y-%m-%d %H:%M:%S")

    lines[#lines + 1] = "-- Area metadata generated by OLC on " .. timestamp
    lines[#lines + 1] = "return {"
    lines[#lines + 1] = '    name   = "' .. area_name .. '",'

    if meta_data.title then
        lines[#lines + 1] = '    title  = "' .. meta_data.title .. '",'
    end
    if meta_data.author then
        lines[#lines + 1] = '    author = "' .. meta_data.author .. '",'
    end
    if meta_data.status then
        lines[#lines + 1] = '    status = "' .. meta_data.status .. '",'
    end

    lines[#lines + 1] = "}"
    lines[#lines + 1] = ""

    return table.concat(lines, "\n")
end

-- ─── File I/O ────────────────────────────────────────────────────────────────

--- Write a room data file to disk.
-- @param area_name string   Area directory name
-- @param room_name string   Room file name (without .lua)
-- @param data table         Room data table
-- @return boolean, string?  Success, error message
function M.write_room_file(area_name, room_name, data)
    local room_id = data.id or (area_name .. "." .. room_name)
    local content = M.generate_room(room_id, data)
    local path = "areas/" .. area_name .. "/rooms/" .. room_name .. ".lua"

    local ok, err = pcall(write_file, path, content)
    if not ok then
        log("error", "CODEGEN_D: Failed to write " .. path .. ": " .. tostring(err))
        if DAEMON and DAEMON.journal then
            DAEMON.journal.error("CODEGEN_D: Failed to write " .. path .. ": " .. tostring(err))
        end
        return false, tostring(err)
    end

    log("debug", "CODEGEN_D: Wrote room file " .. path)
    return true
end

--- Write an area _meta.lua file to disk.
-- @param area_name string
-- @param meta_data table
-- @return boolean, string?
function M.write_meta_file(area_name, meta_data)
    local content = M.generate_meta(area_name, meta_data)
    local path = "areas/" .. area_name .. "/_meta.lua"

    local ok, err = pcall(write_file, path, content)
    if not ok then
        log("error", "CODEGEN_D: Failed to write " .. path .. ": " .. tostring(err))
        if DAEMON and DAEMON.journal then
            DAEMON.journal.error("CODEGEN_D: Failed to write " .. path .. ": " .. tostring(err))
        end
        return false, tostring(err)
    end

    log("debug", "CODEGEN_D: Wrote meta file " .. path)
    return true
end

--- Read a room file and parse it back into a data table.
-- @param area_name string
-- @param room_name string
-- @return table|nil, string?  Data table, or nil + error
function M.read_room_data(area_name, room_name)
    local path = "areas/" .. area_name .. "/rooms/" .. room_name .. ".lua"

    local ok, content = pcall(read_file, path)
    if not ok or not content then
        return nil, "Cannot read " .. path
    end

    local fn, parse_err = load(content)
    if not fn then
        log("error", "CODEGEN_D: Parse error in " .. path .. ": " .. tostring(parse_err))
        return nil, "Parse error: " .. tostring(parse_err)
    end

    local exec_ok, data = pcall(fn)
    if not exec_ok or type(data) ~= "table" then
        log("error", "CODEGEN_D: Execution error loading " .. path)
        return nil, "Execution error"
    end

    return data
end

--- Update exits on an existing room file (merge, not replace).
-- @param area_name string
-- @param room_name string
-- @param new_exits table   { direction = target_id, ... }
-- @return boolean, string?
function M.update_room_exits(area_name, room_name, new_exits)
    local data, err = M.read_room_data(area_name, room_name)
    if not data then
        return false, err
    end

    data.exits = data.exits or {}
    for dir, target in pairs(new_exits) do
        data.exits[dir] = target
    end

    return M.write_room_file(area_name, room_name, data)
end

log("debug", "CODEGEN_D: daemon loaded")

return M
