-- Area metadata, generated by OLC on 2026-08-06 22:19:44.
--
-- `managed` is what lets OLC write here at all. Remove it and every
-- OLC write to this area is refused — which is how a hand-authored
-- area stays safe from a regeneration that would eat its lfuns.
return {
    name     = "thornhollow",
    title    = "Thornhollow",
    author   = "Oxigeon",
    level    = "1-10",
    entrance = "thornhollow.square",
    status   = "live",
    managed  = "olc.v1",
    updated  = "2026-08-06 22:19:44",
}
