-- mudlib/daemons/codegen_d.lua — Authored data, to and from disk.
--
-- Everything OLC writes goes through here. The old version built its output by
-- concatenating strings and knew about exactly five room fields, which produced
-- four distinct failures that all looked like something else:
--
--   * a room title containing `"` produced a file that would not compile, and
--     nothing said so until the next reload;
--   * `light`, `smell`, `sound` and `tags` were *destroyed* on the next `dig`,
--     because the round trip re-emitted only the five it knew;
--   * the multi-line branch indented the closing `]]`, so a description grew
--     four spaces on every read-and-rewrite, for ever;
--   * it reported success for writes that had been refused, because
--     `pcall(write_file, ...)` catches nothing — the efun *returns* failure.
--
-- None of that is fixed here. It is fixed by not being this file's problem:
-- `lib/serialize.lua` decides how a value is written, `lib/schema.lua` decides
-- which fields exist and in what order, and this decides only *where* files go
-- and what a file is made of.
--
-- ─── What a managed area is made of ──────────────────────────────────────────
--
--   game/areas/<name>/
--     _meta.lua     OLC-owned. Carries `managed`, which gates every write.
--     rooms.lua     OLC-owned. An array of flat room data.
--     items.lua     OLC-owned. An array of flat item authoring data.
--     mobs.lua      OLC-owned. An array of mob templates.
--     custom.lua    YOURS. Patches keyed by kind then id. Never read or written
--                   here, and never regenerated.
--
-- The four OLC files are regenerated wholesale, which is only safe because
-- anything that cannot be expressed as data lives in the fifth. See
-- `lib/patch.lua`.

local serialize = require('lib.serialize')
local schema    = require('lib.schema')

local M = {}

--- The format version, and the adoption gate, in one field.
---
--- One field rather than two because they answer the same question: OLC may
--- write here, and this is the shape it will write. An area whose `_meta.lua`
--- lacks it is refused — which is what keeps a hand-authored area safe from a
--- regeneration that would eat its lfuns.
M.MANAGED = "olc.v1"

--- The files OLC owns, and the kind each holds.
M.GENERATED = {
    { file = "rooms", kind = "room" },
    { file = "items", kind = "item" },
    { file = "mobs",  kind = "mob"  },
}

local function log_error(message)
    log("error", message)
    if DAEMON and DAEMON.journal then pcall(DAEMON.journal.error, message) end
end

-- ─── Paths ───────────────────────────────────────────────────────────────────

--- Where an area's files live, rooted explicitly.
---
--- `game:` every time. An unprefixed write means *the mudlib*, which is where
--- every file this daemon ever generated used to land — `mudlib/areas/`, a
--- directory that does not exist, while `dig` reported `game/areas/...` and the
--- loader read `game/areas/`. Nothing OLC created could load.
--- @param area_name string
--- @param file string  "rooms" | "_meta" | ...
--- @return string
function M.path(area_name, file)
    return "game:areas/" .. area_name .. "/" .. file .. ".lua"
end

--- The require-path for one of an area's modules.
--- @param area_name string
--- @param file string
--- @return string
function M.module(area_name, file)
    return "areas." .. area_name .. "." .. file
end

-- ─── Writing ─────────────────────────────────────────────────────────────────

--- The header every generated file carries.
local function header(area_name, what, count)
    return {
        "Generated by OLC on " .. os_date("%Y-%m-%d %H:%M:%S")
            .. " — area '" .. area_name .. "', " .. count .. " " .. what
            .. (count == 1 and "" or "s") .. ".",
        "",
        "DO NOT EDIT. `olc` rewrites this file wholesale and your changes will",
        "be lost. Hand-written behaviour — actions, hooks, lfun descriptions —",
        "goes in custom.lua, which OLC never reads or writes.",
    }
end

--- Write a file and *check the result*.
---
--- `write_file` returns failure rather than raising it, so the old
--- `pcall(write_file, ...)` produced `ok = true, err = false` and reported every
--- refused write as a success. One helper, so there is one place to get it right.
--- @param path string
--- @param content string
--- @return boolean ok, string|nil err
local function write(path, content)
    if type(write_file) ~= "function" then
        return false, "write_file is unavailable"
    end
    local ok, err = write_file(path, content)
    if not ok then
        log_error("CODEGEN_D: failed to write " .. path .. ": " .. tostring(err))
        return false, tostring(err)
    end
    log("debug", "CODEGEN_D: wrote " .. path)
    return true
end

--- Section comments, computed per record.
---
--- A file holds an array of records, and which key starts a component block
--- depends on that record — a lantern has no `-- weapon` line and the sword
--- beside it does. A flat table of comments would put the same one above the
--- same key in every record, or in none.
local function comment_for(kind)
    return function(tbl, path, key)
        -- Top level of one record only. A record inside the file's array has a
        -- breadcrumb like `1`; anything deeper is inside one of its fields, and
        -- a component label belongs above the field, not inside it.
        if path ~= "" and not path:match("^%d+$") then return nil end
        local marks = schema.comments(kind, tbl)
        return marks[key]
    end
end

--- Render one datum of a kind, in schema order, with component section comments.
--- @param kind string
--- @param data table
--- @return string|nil source, string|nil err
function M.render(kind, data)
    return serialize.value(data, {
        order    = schema.orderer(kind),
        comments = comment_for(kind),
    })
end

--- Generate the source for one of an area's data files.
--- @param area_name string
--- @param kind string   "room" | "item" | "mob"
--- @param list table    array of flat data tables
--- @return string|nil source, string|nil err
function M.generate(area_name, kind, list)
    return serialize.module(list, {
        header   = header(area_name, kind, #list),
        order    = schema.orderer(kind),
        comments = comment_for(kind),
    })
end

--- Generate an area's `_meta.lua`.
--- @param area_name string
--- @param meta table  { title, author, level, status }
--- @return string|nil source, string|nil err
function M.generate_meta(area_name, meta)
    meta = type(meta) == "table" and meta or {}
    local out = {
        name    = area_name,
        title   = meta.title or area_name,
        author  = meta.author or "Unknown",
        level   = meta.level,
        -- Where the area starts, for `verify`'s reachability walk. Defaulted
        -- rather than required: `<area>.entrance` is what `olc new area` makes
        -- and what every area here uses, and an area that starts somewhere else
        -- can say so. The alternative — guessing "the room with no inbound
        -- edges" — picks a different room after every edit and makes the orphan
        -- list flap between runs.
        entrance = meta.entrance or (area_name .. ".entrance"),
        status  = meta.status or "building",
        managed = M.MANAGED,
        updated = os_date("%Y-%m-%d %H:%M:%S"),
    }
    return serialize.module(out, {
        header = {
            "Area metadata, generated by OLC on " .. out.updated .. ".",
            "",
            "`managed` is what lets OLC write here at all. Remove it and every",
            "OLC write to this area is refused — which is how a hand-authored",
            "area stays safe from a regeneration that would eat its lfuns.",
        },
        order = function()
            return { "name", "title", "author", "level", "entrance", "status", "managed", "updated" }
        end,
    })
end

--- Write one of an area's data files.
--- @param area_name string
--- @param kind string
--- @param list table
--- @return boolean ok, string|nil err
function M.write_kind(area_name, kind, list)
    local file
    for _, spec in ipairs(M.GENERATED) do
        if spec.kind == kind then file = spec.file end
    end
    if not file then return false, "no generated file holds a '" .. tostring(kind) .. "'" end

    local source, err = M.generate(area_name, kind, list)
    if not source then return false, err end
    return write(M.path(area_name, file), source)
end

--- Write an area's `_meta.lua`.
--- @param area_name string
--- @param meta table
--- @return boolean ok, string|nil err
function M.write_meta(area_name, meta)
    local source, err = M.generate_meta(area_name, meta)
    if not source then return false, err end
    return write(M.path(area_name, "_meta"), source)
end

-- ─── Reading ─────────────────────────────────────────────────────────────────

--- Read one of an area's files back, without registering anything.
---
--- Through `read_file` + `load` rather than `require`, deliberately: `verify`
--- has to be able to ask *what the next reload will do*, and `require` would
--- hand back a cached module that may be several edits behind what is on disk.
--- @param area_name string
--- @param file string
--- @return any value, string|nil err   nil,nil when the file simply is not there
function M.read(area_name, file)
    local path = M.path(area_name, file)
    if type(read_file) ~= "function" then return nil, "read_file is unavailable" end

    local content = read_file(path)
    if not content then return nil, nil end

    local chunk, parse_err = load(content, "@" .. path)
    if not chunk then return nil, "does not compile: " .. tostring(parse_err) end

    local ok, value = pcall(chunk)
    if not ok then return nil, "does not run: " .. tostring(value) end
    return value
end

--- Everything an area's files hold, read from disk.
---
--- The shape `verify` and `olc adopt` both want: what is on disk, not what the
--- registry ended up with. The registry has already collapsed duplicate ids,
--- dropped fields the loader ignored, and applied `custom.lua` — so it cannot
--- answer "what will the next reload do", which is the only question a builder
--- about to save actually has.
--- @param area_name string
--- @return table  { meta, rooms, items, mobs, custom, errors = { {file, message} } }
function M.read_area(area_name)
    local out = { rooms = {}, items = {}, mobs = {}, errors = {} }

    local meta, err = M.read(area_name, "_meta")
    if err then out.errors[#out.errors + 1] = { file = "_meta.lua", message = err } end
    out.meta = type(meta) == "table" and meta or nil

    for _, spec in ipairs(M.GENERATED) do
        local list, list_err = M.read(area_name, spec.file)
        if list_err then
            out.errors[#out.errors + 1] = { file = spec.file .. ".lua", message = list_err }
        elseif type(list) == "table" then
            out[spec.file] = list
        end
    end

    local custom, custom_err = M.read(area_name, "custom")
    if custom_err then
        out.errors[#out.errors + 1] = { file = "custom.lua", message = custom_err }
    end
    out.custom = type(custom) == "table" and custom or nil

    return out
end

--- Is this area OLC-managed?
---
--- Every write consults this. An area that has never been adopted is refused,
--- which is what stops a regeneration eating a hand-authored area's actions and
--- lfun descriptions before anybody has been told they would be lost.
--- @param area_name string
--- @return boolean managed, string|nil why_not
function M.is_managed(area_name)
    local meta = M.read(area_name, "_meta")
    if type(meta) ~= "table" then
        return false, "'" .. area_name .. "' has no _meta.lua, so OLC does not manage it."
    end
    if meta.managed ~= M.MANAGED then
        return false, "'" .. area_name .. "' is not OLC-managed"
            .. (meta.managed and (" (its _meta says '" .. tostring(meta.managed) .. "')") or "")
            .. ". Run `olc adopt " .. area_name .. "` to see what adopting it would change."
    end
    return true
end

log("debug", "CODEGEN_D: daemon loaded")

return M
